### PR TITLE
V 0.2

### PR DESCRIPTION
**Pull request by SaipakhooHooia**
姓名:曾憶珺
http://54.196.144.148:8000/docs#/default/api_attract_api_attractions_get
http://54.196.144.148:8000/api/attractions?page=1
http://54.196.144.148:8000/api/attractions?page=8
http://54.196.144.148:8000/api/attractions?page=0&keyword=溫泉
http://54.196.144.148:8000/api/attractions?page=0&keyword=北投
http://54.196.144.148:8000/api/attraction/50
http://54.196.144.148:8000/api/attraction/60
http://54.196.144.148:8000/api/mrts

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
- Parameter page of attractions API should start from 0.
- nextPage of the last page should be null.
- I have no ideas why your http://54.196.144.148:8000/api/attractions?page=0&keyword=%E5%8C%97%E6%8A%95 and http://54.196.144.148:8000/api/attractions?page=1&keyword=%E5%8C%97%E6%8A%95 and http://54.196.144.148:8000/api/attractions?page=2&keyword=%E5%8C%97%E6%8A%95 all get the same response.
- Naming of nextPage field is incorrect.

**Review by cwpeng — CHANGES_REQUESTED** [review]
http://54.196.144.148:8000/api/attractions?page=0&keyword=%E5%8A%8D%E6%BD%AD should have some attraction data around MRT station.

**Review by cwpeng — CHANGES_REQUESTED** [review]
I don't know which code is your final version. Just keep the final version code in your repository.

**Comment by SaipakhooHooia** [comment]
老師好，V 0.2 是最終版本

**Review by cwpeng — CHANGES_REQUESTED** [review]
You have multiple python files where I don't know which one is your final one. Keep only the final one in your project, you don't need to keep them all.

**Comment by SaipakhooHooia** [comment]
姓名:曾憶珺

老師好，已做以下修改:
1.最終版本V 0.4僅有一個app.py檔案
2.確認網址:
http://54.196.144.148:8000/docs#/default/api_attract_api_attractions_get
http://54.196.144.148:8000/api/attractions?page=1
http://54.196.144.148:8000/api/attractions?page=8
http://54.196.144.148:8000/api/attractions?page=0&keyword=%E5%8A%8D%E6%BD%AD
[http://54.196.144.148:8000/api/attractions?page=0&keyword=溫泉](http://54.196.144.148:8000/api/attractions?page=0&keyword=%E6%BA%AB%E6%B3%89)
[http://54.196.144.148:8000/api/attractions?page=0&keyword=北投](http://54.196.144.148:8000/api/attractions?page=0&keyword=%E5%8C%97%E6%8A%95)
http://54.196.144.148:8000/api/attractions?page=1&keyword=%E5%8C%97%E6%8A%95
http://54.196.144.148:8000/api/attraction/50
http://54.196.144.148:8000/api/attraction/60
http://54.196.144.148:8000/api/mrts

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
